name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kovshenin/sail-deploy@v1
        with:
          passphrase: ${{ secrets.SAIL_PASSPHRASE }}
